### PR TITLE
Django tenants

### PR DESCRIPTION
**Pull request by bruecksen**
@madmooose i implemented a first round of tenants and have it working locally. Maybe it is a good idea if you check out this branch and test it locally as well. Best thing is to start with a fresh database (psql: create database bakeuptenants) and then follow the instructions in the readme to create a first tenant. After that you could load the initial data as stated in the readme as well. Let me know if you need any help. 

ps. everything in under 2 hours of work :))

### CODE REVIEW

**Comment by madmooose** [comment]
If i run `python manage.py create_tenant` i get the following error:
`Traceback (most recent call last):
  File "/home/niels/Projekte/bakeup/bakeup/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/management/commands/create_tenant.py", line 69, in handle
    tenant = self.store_tenant(**tenant_data)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/management/commands/create_tenant.py", line 106, in store_tenant
    tenant = get_tenant_model().objects.create(**fields)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/models.py", line 111, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/models.py", line 198, in create_schema
    call_command('migrate_schemas',
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/management/commands/migrate_schemas.py", line 68, in handle
    executor.run_migrations(tenants=tenants)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/migration_executors/standard.py", line 14, in run_migrations
    run_migrations(self.args, self.options, self.codename, schema_name, idx=idx, count=len(tenants))
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django_tenants/migration_executors/base.py", line 53, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 343, in create_model
    sql, params = self.table_sql(model)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 162, in table_sql
    definition, extra_params = self.column_sql(model, field)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 215, in column_sql
    db_params = field.db_parameters(connection=self.connection)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1004, in db_parameters
    return {"type": self.db_type(connection), "check": self.db_check(connection)}
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1001, in db_type
    return self.target_field.rel_db_type(connection=connection)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 897, in target_field
    return self.foreign_related_fields[0]
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 644, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 632, in related_fields
    return self.resolve_related_fields()
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 936, in resolve_related_fields
    related_fields = super().resolve_related_fields()
  File "/home/niels/Projekte/bakeup/bakeupenv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 615, in resolve_related_fields
    raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
ValueError: Related model 'core.address' cannot be resolved
`

**Comment by bruecksen** [comment]
@madmooose das model musste ich umziehe, hast du `manage.py migrate` vorher gemacht?

**Comment by madmooose** [comment]
Jo, neue Datenbank angelegt und mit migrate befüllt.

**Comment by bruecksen** [comment]
@madmooose kannst du nochmal probieren? Da war wirklich was mit den migrations schief gelaufen. Mit dem fix sollte es jetzt aber passen denke ich.

**Pull request merged**
